---
# Source: cluster-template/templates/appprojects/berg.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: berg
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: berg
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy berg application
  destinations:
    - namespace: berg
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io
    - kind: ClusterRole
      group: rbac.authorization.k8s.io
    - kind: ClusterRoleBinding
      group: rbac.authorization.k8s.io
  sourceRepos:
    - ghcr.io/norelect/charts
    {{- if .Values.challenges.enabled }}
    - {{ .Values.challenges.repo }}
    {{- end }}
    - {{ .Values.infra.repo }}
