---
# Source: cluster-template/templates/appprojects/certificates.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: certificates
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: certificates
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy certificates
  namespaceResourceWhitelist:
    - group: cert-manager.io
      kind: Certificate
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - {{ .Values.infra.repo }}
