---
# Source: cluster-template/templates/appprojects/infra-argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-argocd
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy argocd to the infra-argocd namespace
  destinations:
    - namespace: infra-argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  sourceRepos:
    - https://charts.adfinis.com
    - https://argoproj.github.io/argo-helm
