---
# Source: cluster-template/templates/appprojects/infra-tracing.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-tracing
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-tracing
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy tracing infra
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: policy
      kind: PodSecurityPolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: monitoring.coreos.com
      kind: PrometheusRule
  destinations:
    - namespace: infra-tracing
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://grafana.github.io/helm-charts
