---
# Source: cluster-template/templates/appprojects/infra-authentik.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-authentik
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: helm-infra-argocd
    app.kubernetes.io/component: infra-authentik
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy authentik to the infra-authentik namespace
  destinations:
    - namespace: infra-authentik
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  sourceRepos:
    - https://charts.goauthentik.io
    - {{ .Values.infra.repo }}
