---
# Source: cluster-template/templates/appprojects/misc-argocd-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: misc-argocd-apps
  namespace: infra-argocd
  labels:
    app.kubernetes.io/name: misc-argocd-apps
    app.kubernetes.io/component: infra-argocd
    app.kubernetes.io/managed-by: helm-infra-argocd
spec:
  description: deploy app-of-apps and apps to the infra-argocd namespace
  destinations:
    - namespace: infra-argocd
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
  sourceRepos:
    - https://argoproj.github.io/argo-helm
