{{- if eq .Values.gateway.type "kgateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  # if we call this berg it clashes with the berg api service account
  name: gw-berg
  namespace: berg
spec:
  gatewayClassName: kgateway
  infrastructure:
    annotations:
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
      load-balancer.hetzner.cloud/name: "traefik.{{ .Values.domains.cluster }}"
    parametersRef:
      name: berg
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            app.kubernetes.io/part-of: infra
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            app.kubernetes.io/part-of: infra
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    name: https-chall
    port: 1337
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    name: tls-chall
    port: 31337
    protocol: TLS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: berg
  namespace: berg
spec:
  kube: 
    service:
      extraAnnotations: 
        load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
        load-balancer.hetzner.cloud/name: "berg.{{ .Values.domains.cluster }}"
    envoyContainer:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: ListenerPolicy
metadata:
  name: berg-ccm-policy
  namespace: berg
spec:
  default:
    proxyProtocol: {}
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw-berg
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: berg
  namespace: berg
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw-berg
  upgradeConfig:
    enabledUpgrades:
      - websocket
{{- end }}
