{{- if .Values.gateways.berg.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: berg
  namespace: berg
spec:
  gatewayClassName: kgateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: Same
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    name: https-chall
    port: 1337
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
  - allowedRoutes:
      namespaces:
        from: All
    name: tls-chall
    port: 31337
    protocol: TLS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: berg-gateway-tls
      mode: Terminate
{{- end }}
