---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-logging
  labels:
    app.kubernetes.io/name: infra-logging
    app.kubernetes.io/part-of: infra
    app.kubernetes.io/component: infra
    pod-security.kubernetes.io/enforce: privileged
    prometheus.io/monitor: "true"
