---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: infra-authentik
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: infra
    pod-security.kubernetes.io/enforce: restricted
  name: infra-authentik
