---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-kgateway
  labels:
    app.kubernetes.io/name: infra-kgateway
    app.kubernetes.io/component: infra
    app.kubernetes.io/part-of: infra
    pod-security.admission.k8s.io/enforce: restricted
